### ISSUE TITLE
Gitalk Comment Plugin - Icarus

### ISSUE THREAD

**Issue by ppoffice** [ppoffice/Public-Gitment-Repo#2]
https://blog.zhangruipeng.me/hexo-theme-icarus/Plugins/Comment/gitalk-comment-plugin/ 

 Installation instructions_config.yml1234567891011comment:    type: gitalk    owner: xxxxxxxx         # (required) GitHub user name    repo: xxxxxxxx          # (required) GitHub repository name    cli

**Comment by cckk4467** [comment]
hope this time will succeed

**Comment by KaisLeung** [comment]
test

**Comment by vincewenminli** [comment]
just test

**Comment by sjszues616** [comment]
测试

**Comment by silencecorner** [comment]
nice work

**Comment by Fallen-down** [comment]
ffd

**Comment by Fallen-down** [comment]
ffd

**Comment by Satanya0** [comment]
$\LaTeX$

**Comment by ye17186** [comment]
来自[https://blog.it-follower.com](https://blog.it-follower.com/)测试该评论插件

**Comment by CHN-ChenYi** [comment]
> @ye17186
> 来自[https://blog.it-follower.com](https://blog.it-follower.com/)测试该评论插件

test

**Comment by skks11** [comment]
大苏打 :star:

**Comment by simonisacoder** [comment]
the icon of gitalk comment doesn't work

**Comment by ZhouRuikang015** [comment]
> @cckk4467
> hope this time will succeed
测试
